title: Chaehee Park
url: "https://ChaeheePark.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #
remote_theme: ankitsultana/researcher@gem
footer: yes
footer_url: "https://github.com/ChaeheePark"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "chaeheepark99@gmail.com"
